---

- name: copies 'sysctl.conf'.
  copy: src=sysctl.conf dest=/etc/sysctl.conf mode=0644
  notify: reload sysctl

- name: copies 'ethernet.sysctl.conf'.
  copy: src=ethernet.sysctl.conf dest=/etc/sysctl.d/ethernet.conf
    owner=root group=root mode=0644
  notify: reload sysctl
  when: inventory_file | basename != 'develop'
