---

- name: copies 'mysql-community-release-el6-5.noarch' to '/usr/local/src'.
  copy: src=mysql-community-release-el6-5.noarch.rpm
    dest=/usr/local/src/mysql-community-release-el6-5.noarch.rpm
    owner=root group=root mode=0644

- name: installs mysql-community-server rpm.
  yum: name=/usr/local/src/mysql-community-release-el6-5.noarch.rpm

- name: installs mysql-community-server.
  yum: name=mysql-community-server enablerepo=mysql56-community

- name: copies 'my.cnf' to '/etc'.
  copy: src=my.cnf dest=/etc/my.cnf
    owner=root group=root mode=0644
  notify: restart mysqld

- name: starts mysqld.
  service: name=mysqld state=started enabled=yes

- name: installs MySQL-python.
  yum: name=MySQL-python
