---

- hosts: webservers
  sudo: yes
  gather_facts: no
  tasks:
  roles:
   - role: jre
     tags: [jre, vim, logstash]
     when: inventory_file | basename == 'develop'
   - role: mysql-devel
     tags: [mysql-devel]
   - role: ruby
     tags: [ruby, rails]
   - role: rails
     tags: [rails]
   - role: apache
     tags: [apache]
